In [3]:
import numpy as np
import pandas as pd

In [66]:
# read .csv file into dataframe
df = pd.read_csv('question2_data.csv',header = None)
df

       0   1   2   3
0   9867   4   2   3
1   1234   7   5   2
2   6213   9   7   0
3   1231  12   2   2
4   8821   2   7   7
5   1131   8   0   8
6   7761  10   3   3
7   6831   0  16   0
8   3131  16   0   0
9   3131   0   0  16
10  8424   0   0   0
11  4211   4   4   4

In [67]:
# The data starts from 0 to 11. It automatically ends after reaching 12.
for i in range(0,12):
    print('Team',int(df.iloc[[i],[0]].values),'has',int(df.iloc[[i],[1]].values),'wins,',
          int(df.iloc[[i],[2]].values),'loses, and',int(df.iloc[[i],[3]].values),'ties')
    total_played = int(df.iloc[[i],[1]].values + int(df.iloc[[i],[2]].values) + int(df.iloc[[i],[3]].values))
    print('Total number of games played:',total_played)
    
    # Season is finished if the team played 16 games already
    if total_played == 16:
        print('Season finished')
    else:
        print('Number of games remaining:',16-total_played)
        
    # Calculating winning average
    if int(df.iloc[[i],[1]].values) != 0:
        print('Winning Average is','{:.4f}'.format(int(df.iloc[[i],[1]].values)/total_played))
    else:
        print('Winning Average is','0.0000')
    
    # Comparing if number of games tied is greater than or equal to the number won
    if int(df.iloc[[i],[3]].values) >=int(df.iloc[[i],[1]].values):
        print('Number of games tied is greater than or equal to the number won')
    else:
        print('Number of games tied is not greater than or equal to the number won')
    
    # Comparing if number of games tied is greater than the number lost
    if int(df.iloc[[i],[3]].values) > int(df.iloc[[i],[2]].values):
        print('Number of games tied is greater than the number lost')
    else:
        print('Number of games tied is not greater than the number lost')
        
    # Calculating wip total for each team
    wip_total = int(df.iloc[[i],[1]].values) + int(df.iloc[[i],[3]].values) - 3*int(df.iloc[[i],[2]].values)
    if wip_total < 0:
        print('Wip Total is', 0)
    else:
        print('wip Total is',wip_total)
        
    print('\t')
# printing total number of teams at the end
print('The total number of teams:',i+1)

Team 9867 has 4 wins, 2 loses, and 3 ties
Total number of games played: 9
Number of games remaining: 7
Winning Average is 0.4444
Number of games tied is not greater than or equal to the number won
Number of games tied is greater than the number lost
wip Total is 1

Team 1234 has 7 wins, 5 loses, and 2 ties
Total number of games played: 14
Number of games remaining: 2
Winning Average is 0.5000
Number of games tied is not greater than or equal to the number won
Number of games tied is not greater than the number lost
Wip Total is 0

Team 6213 has 9 wins, 7 loses, and 0 ties
Total number of games played: 16
Season finished
Winning Average is 0.5625
Number of games tied is not greater than or equal to the number won
Number of games tied is not greater than the number lost
Wip Total is 0

Team 1231 has 12 wins, 2 loses, and 2 ties
Total number of games played: 16
Season finished
Winning Average is 0.7500
Number of games tied is not greater than or equal to the number won
Number of games tied is not greater than the number lost
wip Total is 8

Team 8821 has 2 wins, 7 loses, and 7 ties
Total number of games played: 16
Season finished
Winning Average is 0.1250
Number of games tied is greater than or equal to the number won
Number of games tied is not greater than the number lost
Wip Total is 0

Team 1131 has 8 wins, 0 loses, and 8 ties
Total number of games played: 16
Season finished
Winning Average is 0.5000
Number of games tied is greater than or equal to the number won
Number of games tied is greater than the number lost
wip Total is 16

Team 7761 has 10 wins, 3 loses, and 3 ties
Total number of games played: 16
Season finished
Winning Average is 0.6250
Number of games tied is not greater than or equal to the number won
Number of games tied is not greater than the number lost
wip Total is 4

Team 6831 has 0 wins, 16 loses, and 0 ties
Total number of games played: 16
Season finished
Winning Average is 0.0000
Number of games tied is greater than or equal to the number won
Number of games tied is not greater than the number lost
Wip Total is 0

Team 3131 has 16 wins, 0 loses, and 0 ties
Total number of games played: 16
Season finished
Winning Average is 1.0000
Number of games tied is not greater than or equal to the number won
Number of games tied is not greater than the number lost
wip Total is 16

Team 3131 has 0 wins, 0 loses, and 16 ties
Total number of games played: 16
Season finished
Winning Average is 0.0000
Number of games tied is greater than or equal to the number won
Number of games tied is greater than the number lost
wip Total is 16

Team 8424 has 0 wins, 0 loses, and 0 ties
Total number of games played: 0
Number of games remaining: 16
Winning Average is 0.0000
Number of games tied is greater than or equal to the number won
Number of games tied is not greater than the number lost
wip Total is 0

Team 4211 has 4 wins, 4 loses, and 4 ties
Total number of games played: 12
Number of games remaining: 4
Winning Average is 0.3333
Number of games tied is greater than or equal to the number won
Number of games tied is not greater than the number lost
Wip Total is 0

The total number of teams: 12